TECHS = [
    "Python",
    "SQL",
    "JavaScript",
    "JS",
    "Django",
    "REST",
    "GIT",
    "Linux",
    "API",
    "Docker",
    "PostgreSQL",
    "HTML",
    "CSS",
    "OOP",
    "algorithms",
    "data structures",
    "AI",
    "ML",
    "Artificial Intelligence",
    "Machine Learning",
    "asyncio",
    "Flask",
    "React",
    "FastAPI",
    "Numpy",
    "Pandas",
    "Matplotlib",
    "Seaborn",
    "MongoDB",
]